### PR TITLE
Fix/dropdown

### LINKED ISSUE #118: [Bug] Template drop-down menu not centered
### Current Behavior

image
The drop down menu for templates is not centered.

### Relevant log output

_No response_

### Expected Behavior

The options in the menu should either be centered, or aligned with either side of the boundaries.

### Changes Needed

Center the text in the drop down menu or align all the text to one side.

### Location of Issue

Most likely inside App.tsx.

### Code Snippets

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jess-lowe**
### Changes

Describe the Pull Request here. Add any references and info to help reviewers understand your changes.

- Changed the html type from select and options to simple divs and links. CSS acts weirdly with select components due to their nature being a shadow DOM element or something, so made it an on-hover event instead. 

### Tests applied

What testing has been applied to validate changes are accurate and correct

- Localhosted and clicked the different dropdowns

### Issue ticket number(s)

Enter the issue numbers resolved by this pull request

-  Closes #118 

### Checklist

- [ ] Documented
- [ ] Linting tests successful
- [ ] merge updated prod branch into development branch

### CODE REVIEW

**Review by rhun558 — APPROVED** [review]
LGTM!

File: src/components/App.tsx [hunk 1]
```diff
@@ -188,16 +196,41 @@ function App() {
...
-          <option value="Article">News Article</option>
-          <option value="Research Paper">Research Paper</option>
-          <option value="Poster">Poster</option>
-        </select>
+        <div className="dropdown">
+          <button id="dropbtn" className="dropbtn">
+            Template
+          </button>
+          <div className="dropdown-content">
+            <a
```
Comment (mwan391) [inline src/components/App.tsx:204]: LGTM. Code is easy to read

**Review by mwan391 — APPROVED** [review]
